### ISSUE TITLE
Automate extraction of member list from database

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#16]
At the moment one has to do this by hand:
- Go to db server (or server with access to db server)
- Run the scripts/members.sql
- scp the csv onto local machine and add to source repo (in data) so others have access to it

**Comment by teajaymars** [comment]
We can't automate the action of scp'ing it into the repo. Rather than generating the output to /var/tmp, can't we put it in the published /www/ folder somewhere, almost like an API hook?
http://okfn.org/api/members.csv ... something like that.
Then a file in the repo could just document the existence of that file.

**Comment by teajaymars** [comment]
Not fully verified (will do in 45 mins...) but http://okfn.org/dashboard/cache/okfn_members.csv should update at ten-past-the-hour every hour.
To do this, the frontend needs to ssh into the backend, so I generated a key-pair for it and authorised it on the backend.

**Comment by teajaymars** [comment]
Solution modified. Frontend does not SSH into backend, but creates a remote client connection and executes the members.sql query. 

Because SELECT INTO OUTFILE does not work over remote connections, the result is piped through SED to create a CSV file, and fed into the public file in /dashboard/cache/.

This runs once per hour. The (eventual) dashboard server can run a cron job to collect this file over HTTP every hour and absorb changes into its webstore.
