### ISSUE TITLE
Rework members map

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#21]
- Run off webstore person table
- Can not have **1Mb** openlayers file
- Convert into backbone view and integrate into overall app

**Comment by napo** [comment]
A good solution can be use mapserver
We need to install it (it's run like a CGI).
This can produce a layer server side, and we can offer, on the browser, only the png file over the map.
This open a "problem" with the interaction: where is the user click, we need to contact mapserver and ask the information.
It isn't difficult, but we need to work.

**Comment by rufuspollock** [comment]
Sounds interesting napo but the aim here is to have something that deployable with minimal dependencies and adding a mapserver to the mix will significantly increase complexity i would imagine :-)

**Comment by teajaymars** [comment]
No longer necessary; a better rebuild was constructed (670kb including images) in @ eee462908a242e535185e2505721416dbf7d0580

**Comment by teajaymars** [comment]
Sorry: THIS issue should be open; gh-22 can be closed.
Reopening this issue.

**Comment by teajaymars** [comment]
1: Still outstanding.
2: Done, got a custom build in the repo of 280kb
3: Done. Map responds to changes in the members collection.

**Comment by elemoine** [comment]
I'm trying to make sense of this issue.

@napo mentioned MapServer as a solution, but this assumes the problem was the number of member objects to render in the map. But I'm not sure that's the problem @rgrp has raised with this issue. It seems to me that @rgrp was talking about the size of the OpenLayers file – addressed with eee4629. @rgrp, can you confirm?

"Run off webstore person table" seems to be done already, no?

I'm not sure about the "Convert to backbone view and integrate with overall app" item. Has it been addressed already?

**Comment by rufuspollock** [comment]
FIXED. (Mostly and time for a new ticket if more to be done).
