### ISSUE TITLE
okfn-labs mailing list not listed on dashboard for labs

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#43]
See http://okfnlabs.org/dashboard/#project/labs

BTW: would love to fix this myself if there were instructions (have i missed them?) :-)

**Comment by teajaymars** [comment]
This is a bug: See: 

https://github.com/okfn/dashboard/blob/master/app/projects.coffee

The `labs` entry contains three mailing lists, though none of them are showing up -- so it is 90% likely to be the API failing (perhaps because of the list being renamed) rather than a flaw in the Dashboard. I can fix it later in the week when I sit down to blast out a set of Dashboard issues.

No "instructions" exist per se, but the code has comments (could always use more...). I could write up developer instructions, they would be something like:
- Install http://brunch.io
- Clone master
- run `npm start`
- Do coding and stuff
- Deploy static output folder `/public` to `gh-pages` branch.

**Comment by rufuspollock** [comment]
Thanks for update Tom - really useful.

For clarify, by instructions I meant more along lines of as a [non-dev user how do i add a project/service to the dashboard](https://docs.google.com/document/d/16rFPJUZIYnAvSvyAPYjgnHdxnPk0OMOwVT87Z2qyCv0/edit#heading=h.873jvcgcuh14)
